blog_ejemplo/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('detalle/<int:pk>', views.PostDetailView.as_view(), name='detalle'),
    path('crear', views.post_crear, name='crear'),
]

blog_ejemplo/blog_ejemplo/urls.py
from django.contrib import admin
from django.urls import path, include
#Se necesitan para obtener las imagenes en desarrollo
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('gestion_usuarios.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#Se incluye esta linea para poder acceder a las imagenes del trabajo

blog_ejemplo/gestion_usuarios/urls.py
from django.conf.urls import url
from . import views
app_name = 'gestion_usuarios'

urlpatterns = [
    url('registrar/', views.registrar, name='registrar'),
    url('login/', views.usuario_login, name='login'),
    url('logout/', views.usuario_logout, name='logout'),
]

blog_ejemplo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>

<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Ejemplo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAccesos"
                aria-controls="navbarAccesos" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarAccesos">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuario:index' %}">index</a></li>
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuario:login' %}">iniciar sesión</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuario:registrar' %}">registrar</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuario:logout' %}">logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>